# ======
# Project Details
# ======
name: jaffle_shop
version: 0.1
config-version: 2
profile: dbt_dwh_models
require-dbt-version: [">=1.0.0", "<2.0.0"]

# ======
# File Path Configs
# ======
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
macro-paths: [macros]
target-path: target

models:
  jaffle_shop:
    marts:
      materialized: table
    staging:
      materialized: view
